### PR TITLE
Loading screen services

### PR DESCRIPTION
**Pull request by kingfisher13**
Question on this. Right now it seems there is a bug where you can only set the backdrop (i.e. whether you can close by click or not) once and only once. Not sure of a way around this but I'll keep investigating it.

Most users though, will read the intro/about first, and then click close (which only shows after the neighborhood layer is finished loading), which should give plenty of time.

### CODE REVIEW

**Comment by kingfisher13** [comment]
Did you want me to include actual content? If so, has the client sent it yet?

**Comment by davidheyman** [comment]
In order for this to function like a loading screen, we need to do 2 things:
1. Prevent the user from closing it until the neighborhoods polygon has finished loading
2. Tell them that they're waiting for something to load

@bcsheesley Any ideas on what do about the second one? Is a spinny + "Loading" under the content enough to make it work?

**Comment by kingfisher13** [comment]
I apologize if this ends up being a nasty merge.

**Comment by kingfisher13** [comment]
@bcsheesley Any ideas for indicators while the neighborhood layers load?

**Comment by kingfisher13** [comment]
Ready for merging now.

**Comment by davidheyman** [comment]
@kingfisher13 I'm not seeing the spinny or close icons on this. Is that a configuration problem on my end?

**Comment by kingfisher13** [comment]
@davidheyman That's because this branch doesn't have the font-awesome stuff included. Merge it and the fonts should show up. I'm still getting used to what work needs to be done on which branch and how to think through that earlier in the process. Sorry.

**Pull request merged**
