### PR TITLE
Added link to council webpage and switched icons font

### PR DESCRIPTION
**Pull request by kingfisher13**

### CODE REVIEW

**Comment by davidheyman** [comment]
@kingfisher13 Two quick changes here:
1. Could you add both the spinny and layers icons to the HTML and use a `.loading` CSS class to switch the visibility between the two?
2. For now, only use the spinny loader for loading additional layers. Once we know what we're doing with the intro screen, we'll figure out a different loader for the neighborhoods since we'll want to restrict all interactions before those are loaded.

**Comment by kingfisher13** [comment]
1. Couldn't use a pure CSS solution because that breaks the fontawesome spinner. See here: https://github.com/FortAwesome/Font-Awesome/issues/729  I did simplify the code to a jQuery toggle method call. Does that suffice?
2. Done.

**Comment by davidheyman** [comment]
1 quick small fix on this one:

bcworkshop_-_services

The layer switcher is in a `.btn-group` which is why the corners on the right side aren't rounded. Can you move it out of the button group and fix the shorted-sighted CSS that will make it flow onto a different line?

**Comment by davidheyman** [comment]
Scratch that diagnosis. The `.btn-group` looks fine on a different branch so the issue must be coming from somewhere else.

**Comment by kingfisher13** [comment]
The square corners are fixed. It was missing some HTML that Bootstrap was looking for.

**Pull request merged**
